In [2]:
import pandas as pd
from pycaret.regression import setup, compare_models, create_model, tune_model

In [3]:
df = pd.read_csv("../Datas/data.csv").drop(["datetime"], axis=1)

In [3]:
my_setup = setup(data = df, target="count",fold_shuffle=True)

In [4]:
best_model = compare_models()
best_model

LGBMRegressor(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
              importance_type='split', learning_rate=0.1, max_depth=-1,
              min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
              n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
              random_state=8232, reg_alpha=0.0, reg_lambda=0.0, silent='warn',
              subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

In [5]:
rf = create_model('rf')

In [8]:
tunned_rf = tune_model(rf)

In [9]:
tunned_rf

RandomForestRegressor(bootstrap=False, ccp_alpha=0.0, criterion='mse',
                      max_depth=10, max_features='log2', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0,
                      min_impurity_split=None, min_samples_leaf=6,
                      min_samples_split=9, min_weight_fraction_leaf=0.0,
                      n_estimators=150, n_jobs=-1, oob_score=False,
                      random_state=8232, verbose=0, warm_start=False)